import React from 'react'
import { ArrowUpRightIcon, CalendarDaysIcon, UsersRoundIcon } from 'lucide-react'
import { SectionTitle } from '../components/SectionTitle'

const committees=[
  {name:'Planeación e Innovación',lead:'Carlos Andrés Pardo',members:7,next:'16 may · Laboratorio de proyectos',activity:'Matriz de iniciativas 2026 actualizada',color:'bg-night'},
  {name:'Bienestar',lead:'Diana Marcela Ortiz',members:5,next:'15 may · Sesión virtual',activity:'Convocatoria taller de salud mental',color:'bg-gold'},
  {name:'Comunicaciones',lead:'Ana Sofía Méndez',members:4,next:'20 may · Sala de medios',activity:'Boletín sindical de abril publicado',color:'bg-brick'},
  {name:'Defensa de Derechos',lead:'Jorge Iván Salcedo',members:6,next:'22 may · Sala 3A',activity:'Acompañamiento a 2 solicitudes activas',color:'bg-emerald-600'},
]
export function ComitesPage(){return <div className="mx-auto max-w-[1440px]"><SectionTitle eyebrow="Trabajo colaborativo" title="Comités" description="Espacios de participación para la gestión y bienestar de las y los afiliados." action={<button className="rounded-xl border border-ink/12 bg-white px-4 py-2.5 text-sm font-semibold text-night hover:border-night">Gestionar integrantes</button>}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{committees.map((committee)=><article key={committee.name} className="overflow-hidden rounded-2xl border border-ink/[0.08] bg-white shadow-[0_6px_22px_rgba(15,27,61,0.04)]"><div className={`h-1.5 ${committee.color}`}/><div className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-canvas text-night"><UsersRoundIcon className="h-5 w-5"/></div><button aria-label={`Abrir ${committee.name}`} className="rounded-lg p-1 text-ink/40 hover:bg-canvas hover:text-night"><ArrowUpRightIcon className="h-4 w-4"/></button></div><h2 className="mt-5 font-display text-lg font-semibold leading-snug text-ink">{committee.name}</h2><p className="mt-2 text-xs text-ink/55">Coordinación: <span className="font-semibold text-ink/75">{committee.lead}</span></p><div className="mt-5 border-y border-ink/[0.07] py-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-ink/40">Actividad reciente</p><p className="mt-1 text-xs leading-relaxed text-ink/65">{committee.activity}</p></div><div className="mt-4 flex items-center justify-between text-xs"><span className="flex items-center gap-1.5 text-ink/55"><UsersRoundIcon className="h-3.5 w-3.5 text-gold"/>{committee.members} miembros</span><span className="flex items-center gap-1.5 text-ink/55"><CalendarDaysIcon className="h-3.5 w-3.5 text-gold"/>{committee.next}</span></div></div></article>)}</div><section className="mt-6 rounded-2xl bg-night px-6 py-6 text-white"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-gold">Participación activa</p><h2 className="mt-1 font-display text-xl font-semibold">22 afiliados aportan desde los comités</h2><p className="mt-2 text-sm text-white/60">El 7% de la base sindical participa en al menos un espacio de trabajo.</p></div><button className="w-fit rounded-xl bg-gold px-4 py-2.5 text-sm font-semibold text-night hover:bg-gold-soft">Ver programación</button></div></section></div>}
