import React from 'react'
import { DownloadIcon, TrendingUpIcon } from 'lucide-react'
import { Bar, BarChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { SectionTitle } from '../components/SectionTitle'
import { cashFlow, membershipTrend } from '../data/mockData'

const attendance=[{name:'Asamblea ordinaria',value:76},{name:'Asamblea extraordinaria',value:63},{name:'Junta directiva',value:92},{name:'Comités',value:58}]
export function ReportesPage(){return <div className="mx-auto max-w-[1440px]"><SectionTitle eyebrow="Análisis institucional" title="Reportes" description="Indicadores consolidados para la toma de decisiones de la organización." action={<button className="inline-flex items-center gap-2 rounded-xl bg-night px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-night/15"><DownloadIcon className="h-4 w-4"/>Exportar PDF</button>}/><div className="grid gap-6 xl:grid-cols-2"><ReportCard title="Tendencia de afiliación" detail="Evolución mensual de afiliados activos"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={membershipTrend} margin={{top:8,right:5,bottom:0,left:-25}}><XAxis dataKey="month" tick={{fontSize:11,fill:'#768094'}} axisLine={false} tickLine={false}/><YAxis domain={[290,315]} tick={{fontSize:11,fill:'#768094'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e8e7e2',fontSize:12}}/><Line type="monotone" dataKey="total" stroke="#0F1B3D" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div></ReportCard><ReportCard title="Comparativo financiero" detail="Ingresos y egresos acumulados del primer semestre"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={cashFlow} margin={{top:8,right:5,bottom:0,left:-25}}><XAxis dataKey="month" tick={{fontSize:11,fill:'#768094'}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11,fill:'#768094'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e8e7e2',fontSize:12}}/><Bar dataKey="income" fill="#0F1B3D" radius={[4,4,0,0]} barSize={14}/><Bar dataKey="expense" fill="#C9973B" radius={[4,4,0,0]} barSize={14}/></BarChart></ResponsiveContainer></div></ReportCard><section className="rounded-2xl border border-ink/[0.08] bg-white p-5 xl:col-span-2"><div className="flex items-start justify-between"><div><h2 className="font-display text-base font-semibold">Participación por espacio</h2><p className="mt-1 text-xs text-ink/50">Asistencia registrada en las últimas actividades institucionales</p></div><TrendingUpIcon className="h-5 w-5 text-gold"/></div><div className="mt-6 grid gap-5 md:grid-cols-4">{attendance.map((item)=><div key={item.name}><div className="flex h-20 items-end rounded-xl bg-canvas px-2 pb-2"><div className="w-full rounded-md bg-night" style={{height:`${item.value}%`}}/></div><div className="mt-3 flex justify-between gap-2"><span className="text-xs text-ink/60">{item.name}</span><span className="text-xs font-semibold text-ink">{item.value}%</span></div></div>)}</div><p className="mt-6 border-t border-ink/[0.07] pt-4 text-xs text-ink/50">Fuente: registros de asistencia y actas de sesión del periodo enero–abril 2026.</p></section></div></div>}
function ReportCard({title,detail,children}:{title:string;detail:string;children:React.ReactNode}){return <section className="rounded-2xl border border-ink/[0.08] bg-white p-5"><h2 className="font-display text-base font-semibold">{title}</h2><p className="mt-1 text-xs text-ink/50">{detail}</p><div className="mt-4">{children}</div></section>}
